// Generated by gencpp from file mymsgs_module/car_command.msg
// DO NOT EDIT!


#ifndef MYMSGS_MODULE_MESSAGE_CAR_COMMAND_H
#define MYMSGS_MODULE_MESSAGE_CAR_COMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mymsgs_module
{
template <class ContainerAllocator>
struct car_command_
{
  typedef car_command_<ContainerAllocator> Type;

  car_command_()
    : throttle(0.0)
    , steering(0.0)  {
    }
  car_command_(const ContainerAllocator& _alloc)
    : throttle(0.0)
    , steering(0.0)  {
  (void)_alloc;
    }



   typedef double _throttle_type;
  _throttle_type throttle;

   typedef double _steering_type;
  _steering_type steering;





  typedef boost::shared_ptr< ::mymsgs_module::car_command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mymsgs_module::car_command_<ContainerAllocator> const> ConstPtr;

}; // struct car_command_

typedef ::mymsgs_module::car_command_<std::allocator<void> > car_command;

typedef boost::shared_ptr< ::mymsgs_module::car_command > car_commandPtr;
typedef boost::shared_ptr< ::mymsgs_module::car_command const> car_commandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mymsgs_module::car_command_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mymsgs_module::car_command_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mymsgs_module::car_command_<ContainerAllocator1> & lhs, const ::mymsgs_module::car_command_<ContainerAllocator2> & rhs)
{
  return lhs.throttle == rhs.throttle &&
    lhs.steering == rhs.steering;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mymsgs_module::car_command_<ContainerAllocator1> & lhs, const ::mymsgs_module::car_command_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mymsgs_module

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mymsgs_module::car_command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mymsgs_module::car_command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mymsgs_module::car_command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mymsgs_module::car_command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mymsgs_module::car_command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mymsgs_module::car_command_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mymsgs_module::car_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "39f463d271c2ca10c14182802c72c029";
  }

  static const char* value(const ::mymsgs_module::car_command_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x39f463d271c2ca10ULL;
  static const uint64_t static_value2 = 0xc14182802c72c029ULL;
};

template<class ContainerAllocator>
struct DataType< ::mymsgs_module::car_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mymsgs_module/car_command";
  }

  static const char* value(const ::mymsgs_module::car_command_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mymsgs_module::car_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 throttle          # throttle pedal, 1->full acceleration, -1->full brake (adimensional)\n"
"float64 steering    # wheels steering angle                                (rad)\n"
;
  }

  static const char* value(const ::mymsgs_module::car_command_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mymsgs_module::car_command_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.throttle);
      stream.next(m.steering);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct car_command_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mymsgs_module::car_command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mymsgs_module::car_command_<ContainerAllocator>& v)
  {
    s << indent << "throttle: ";
    Printer<double>::stream(s, indent + "  ", v.throttle);
    s << indent << "steering: ";
    Printer<double>::stream(s, indent + "  ", v.steering);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MYMSGS_MODULE_MESSAGE_CAR_COMMAND_H
