# PID parameters
K: 0.1
I: 0.0000

# Controller
look_ahead_time_longitudinal: 3.5
look_ahead_time_lateral: 1.1
min_look_ahead_distance: 3.5
max_speed: 5.0
min_speed: 2.5
b_filter_throttle : [
    0.159341287490797096,
    0.681317425018405753,
    0.159341287490797096,
]
b_filter_steering: [
    0.159341287490797096,
    0.681317425018405753,
    0.159341287490797096,
]

# Map Directory
# map_dir: /home/david/Documents/Tecnico/SecondQuarter/Robotics/Lab2/Robotics2/autonomous_fiat/src/control/src/maps/trackdrive.yaml
# map_dir: /home/david/Documents/Tecnico/SecondQuarter/Robotics/Lab2/Robotics2/autonomous_fiat/src/control/src/maps/test_map.yaml
# map_dir: '/home/david/Documents/Tecnico/SecondQuarter/Robotics/Lab2/Robotics2/autonomous_fiat/src/guidance/find_path/images/tecnico.yaml'
map_dir: 0

# Simulation
simul: 2 # 0 for no simulation, 1 for abstract simulation (velocity as input), 2 for real simulation (throttle as input)
latitude: 38.737097
longitude: -9.138015
altitude: 92

# Car paarmeters
car_parameters:
  L: 2.46
  Lf: 0.74
  Lr: 0.6
  m: 1190
  g: 9.81
  Width: 1.66
  Length: 3.8
  aero_drag: 0.34
  r_wheel: 0.292
  MaxTorque: 165 #Nm
  GR: 5 #0.87
  eta: 0.85 #effiency
  Cr: 0.01
  BrakingTorque: 300