// Generated by gencpp from file control_module/control_command.msg
// DO NOT EDIT!


#ifndef CONTROL_MODULE_MESSAGE_CONTROL_COMMAND_H
#define CONTROL_MODULE_MESSAGE_CONTROL_COMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace control_module
{
template <class ContainerAllocator>
struct control_command_
{
  typedef control_command_<ContainerAllocator> Type;

  control_command_()
    : throttle(0.0)
    , steering_angle(0.0)  {
    }
  control_command_(const ContainerAllocator& _alloc)
    : throttle(0.0)
    , steering_angle(0.0)  {
  (void)_alloc;
    }



   typedef double _throttle_type;
  _throttle_type throttle;

   typedef double _steering_angle_type;
  _steering_angle_type steering_angle;





  typedef boost::shared_ptr< ::control_module::control_command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::control_module::control_command_<ContainerAllocator> const> ConstPtr;

}; // struct control_command_

typedef ::control_module::control_command_<std::allocator<void> > control_command;

typedef boost::shared_ptr< ::control_module::control_command > control_commandPtr;
typedef boost::shared_ptr< ::control_module::control_command const> control_commandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::control_module::control_command_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::control_module::control_command_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::control_module::control_command_<ContainerAllocator1> & lhs, const ::control_module::control_command_<ContainerAllocator2> & rhs)
{
  return lhs.throttle == rhs.throttle &&
    lhs.steering_angle == rhs.steering_angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::control_module::control_command_<ContainerAllocator1> & lhs, const ::control_module::control_command_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace control_module

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::control_module::control_command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control_module::control_command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_module::control_command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_module::control_command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_module::control_command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_module::control_command_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::control_module::control_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9f3b540e5265853adbd53f61d05b89c6";
  }

  static const char* value(const ::control_module::control_command_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9f3b540e5265853aULL;
  static const uint64_t static_value2 = 0xdbd53f61d05b89c6ULL;
};

template<class ContainerAllocator>
struct DataType< ::control_module::control_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "control_module/control_command";
  }

  static const char* value(const ::control_module::control_command_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::control_module::control_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 throttle          # throttle pedal, 1->full acceleration, -1->full brake (adimensional)\n"
"float64 steering_angle    # wheels steering angle                                (rad)\n"
;
  }

  static const char* value(const ::control_module::control_command_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::control_module::control_command_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.throttle);
      stream.next(m.steering_angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct control_command_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::control_module::control_command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::control_module::control_command_<ContainerAllocator>& v)
  {
    s << indent << "throttle: ";
    Printer<double>::stream(s, indent + "  ", v.throttle);
    s << indent << "steering_angle: ";
    Printer<double>::stream(s, indent + "  ", v.steering_angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROL_MODULE_MESSAGE_CONTROL_COMMAND_H
